version: 2

sources:
  - name: seeds
    schema: tap_dbt_artifacts_tests

    freshness:
      warn_after: {count: 1, period: hour}
      error_after: {count: 2, period: hour}
    loaded_at_field: _loaded_at

    tables:
      - name: customers
      - name: orders
